### ISSUE TITLE
Lots of icon are missing

### ISSUE THREAD

**Issue by BananaSoftwaree** [Wolfyxon/wolfyxon.github.io#1]
Look at these!

![image](https://user-images.githubusercontent.com/93658686/154214942-5d54f783-1d66-4677-a1d1-693baf171235.png)

![image](https://user-images.githubusercontent.com/93658686/154214957-cbeb6212-e3bd-4b71-a07e-ea884e9dcda2.png)

Also plexus are disappear after a while
That's all

And remove the funny meme hyperlink pls 😠

**Comment by Wolfyxon** [comment]
The icons are missing because these projects have no icons ¯\_(ツ)_/¯
And these memes are funny what's wrong?

**Comment by BananaSoftwaree** [comment]
> The icons are missing because these projects have no icons ¯_(ツ)_/¯

Take icon from the internet or draw yourself
Too weird when the image are missing

> And these memes are funny what's wrong?

MEME IS FUNNY??
You once again Rich Roll me 😠

**Comment by BananaSoftwaree** [comment]
Also have you check the plexus bug
I don't see you mention it

**Comment by Wolfyxon** [comment]
The plexus disappears when the browser tab is not open for too long, it's because JavaScript cannot get window size

I'll try to fix this later
