### ISSUE TITLE
My project Cards 

### ISSUE THREAD

**Issue by utkarshgoel10** [Wolfyxon/wolfyxon.github.io#2]
Hey!
I saw your website, and I think those project cards can be made better and aligned equally. 
Think you can assign me this issue, I'd be glad to work on this!!

**Comment by Wolfyxon** [comment]
Yeah their positions are breaking on some browsers. I'm on Firefox and they look normally for me:
![image](https://user-images.githubusercontent.com/58263600/195676408-68965302-851d-4925-9435-4fdc28fa5440.png)
I always forget to fix that

**Comment by Wolfyxon** [comment]
I thought https://github.com/Wolfyxon/wolfyxon.github.io/commit/48d689cbae553f059f9342f1924de134bb641b07 was gonna fix that

**Comment by Wolfyxon** [comment]
![image](https://user-images.githubusercontent.com/58263600/195697429-cb665d44-aa2d-4a07-94ec-46b2b69eb800.png)
I'm on Chromium now and this is what happens, I assigned you

**Comment by Wolfyxon** [comment]
Fixed with https://github.com/Wolfyxon/wolfyxon.github.io/commit/c3ab86c87c8461b9dcff7f3a4de9ca76dbe1a633
Weird that I had `height: 340px;` commented.
